- name: create directory for disc_backend app
  file:
    path: /etc/docker/compose/disc_backend
    state: directory
    mode: 0770
    owner: root
    group: docker

- name: deploy docker-compose.yml for disc_backend app
  template:
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/disc_backend/docker-compose.yml
    mode: 0640
    owner: root
    group: docker
  notify:
    - restart disc_backend

- name: start & enable disc_backend service
  service:
    name: docker-compose@disc_backend
    # Сервис должен запускаться после перезагрузки
    enabled: yes
    # Сервис должен запуститься или быть уже запущен
    state: started

# Требуется для модуля docker_container
# https://docs.ansible.com/ansible/latest/modules/docker_container_module.html#requirements
- name: install python modules
  apt:
    name:
      - python3-docker
    update_cache: yes

# Требуется чтобы все обработчики (handlers) отработали немедленно,
# не дожидаясь обычных точек синхронизации
# https://docs.ansible.com/ansible/latest/modules/meta_module.html#parameters
- name: flush handlers
  meta: flush_handlers

- name: apply database migrations
  docker_container:
    name: db_migrator
    image: "{{ disc_backend_image }}"
    command: ["disc_backend-db", "upgrade", "head"]
    networks:
      - name: disc_backend_default
    auto_remove: yes
    networks_cli_compatible: yes
    env:
      DISC_PG_URL: postgresql://{{ disc_backend_pg_user }}:{{ disc_backend_pg_password }}@postgres/{{ disc_backend_pg_dbname }}
